version: '3.8'
services:
  loan-api:
    container_name: loan_api
    build:
      context: .
      dockerfile: Dockerfile
    image: loan:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_CONNECTION_STRING: jdbc:postgresql://postgres:5432/bankdb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_SCHEMA: bank
      PAYMENT_SERVICE_URL: http://payment-api:8082
      PAYMENT_SERVICE_SQS: http://localstack:4566/000000000000/process-payment
      LOCALSTACK_URL: http://localstack:4566
      AWS_ACCESS_KEY: faker
      AWS_SECRET_KEY: faker
    networks:
      - bank_iac_bank_network

networks:
  bank_iac_bank_network:
    external: true