version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_bank
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    container_name: flyway_migration
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres:5432/bankdb -schemas=bank -user=postgres -password=password migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

  localstack:
    image: localstack/localstack:latest
    container_name: bank_stack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./scripts:/etc/localstack/init/ready.d/"

volumes:
  postgres_data: